# Generated by Django 5.0.4 on 2024-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(choices=[('finance', 'Finance'), ('machin learning', 'Machin learning'), ('robotic', 'Robotic'), ('search AI', 'Search AI')], max_length=100)),
                ('image', models.ImageField(upload_to='image/innovation/')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
