# Generated by Django 5.0.4 on 2024-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_innovationmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
