# Generated by Django 5.0.4 on 2024-04-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_ourservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurService',
            new_name='Service',
        ),
    ]
