# Generated by Django 5.0.4 on 2024-04-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blog_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_list',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs'),
        ),
    ]
