# Generated by Django 5.0.4 on 2024-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
    ]
