# Generated by Django 5.0.4 on 2024-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_create_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
