# Generated by Django 5.0.4 on 2024-04-21 17:30

import birthday.fields
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('about_me', models.TextField()),
                ('skills', models.CharField(choices=[('developer', 'Developer'), ('django', 'Django'), ('css', 'CSS'), ('html', 'HTML'), ('git', 'Git'), ('python', 'Python'), ('machine_learning', 'Machine Learning')], max_length=50)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('gmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birthday_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birthday', birthday.fields.BirthdayField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('B_M', django.db.models.manager.Manager()),
            ],
        ),
    ]
