# Generated by Django 5.0.4 on 2024-04-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
